#  gitlab-runner register
# https://gitlab.com/togop/3DPolyS-LE
# locally run it with:  gitlab-runner exec docker test
# how to test locally: https://medium.com/@umutuluer/how-to-test-gitlab-ci-locally-f9e6cef4f054
image:
  togop/gcc_gfortran_mpi_hdf5_python:latest

before_script:
  - echo "PATH=$PATH:/root/miniconda3/bin/" >> ~/.bashrc
  - source ~/.bashrc
  - make env
  - conda init bash
  - conda activate py3dpolys_le
  - make all
  - echo "conda activate py3dpolys_le" >> ~/.bashrc
  #- cat ~/.bashrc
  - source ~/.bashrc

test:
  script:
    - pwd
    #- cd bin
    - ls -la
    - 3dpolys_le_runner --help
    - python --version
    - echo 'Start tests ...'
    - 3dpolys_le_runner run -o ./out_8860 -i ./test/test_shell_input.cfg
    - ../test.sh ./out_8860/config.out
    - ls -la ./out_8860
    - ls -la ./out_8860/r2.84
    - ../test.sh ./out_8860/r2.84/Chip.out
    - ../test.sh ./out_8860/r2.84/xyzconfig.out
    - ../test.sh ./out_8860/r2.84/hic_001.hdf5
    - ../test.sh ./out_8860/r2.84/hic_002.hdf5
