#  gitlab-runner register
# https://gitlab.com/
# locally run it with:  gitlab-runner exec docker test
#   troubleshooting: sudo ln -s "$HOME/.docker/run/docker.sock" /var/run/docker.sock
# docker run -d --name gitlab-runner --restart always -v /srv/gitlab-runner/config:/etc/gitlab-runner -v /var/run/docker.sock:/var/run/docker.sock gitlab/gitlab-runner:latest
# how to test locally: https://medium.com/@umutuluer/how-to-test-gitlab-ci-locally-f9e6cef4f054

stages:
#  - build
  - test
  - publish
  - production

image:
  togop/gcc_gfortran_openmpi_hdf5_python_uv:2025-05-31
#  togop/gcc_gfortran_openmpi_hdf5_python_mamba:2023-06-16
#  debian:stable-slim

before_script:
    # - apt-get update
    - echo "$SYLABS_TOKEN"
    - echo "PATH=$PATH:/opt/uv" >> ~/.bashrc
    - source ~/.bashrc
#    - mamba update -n base mamba
#    - mamba init bash
#    - source ~/.bashrc
    - which uv
    - uv --version
#    - pip --version
#    - mamba --version
    - make venv
    - source .venv/bin/activate
    - python --version
#    - mamba install -y -q cooler pyranges -c bioconda
#    - mamba install -y -q numpy pandas matplotlib scipy dask h5py filelock seaborn -c conda-forge
#    - mamba install -y -q build
#    - mamba install -y -q cmake
    #- python -m ensurepip --upgrade
    - make all
    - export OMPI_ALLOW_RUN_AS_ROOT=1
    - export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

test:
  stage: test
  script:
    - pwd
    - ls -la
    - 3dpolys_le_runner --help
    - python --version
    - echo 'Start tests ...'
    # pytest
    - make test
    - ls -la out-Nlef200-km0.0027-bd0_im-z_z-loop
    - ls -la out-Nlef200-km0.0027-bd0_im-z_z-loop/r2.84
    # shell test
    - 3dpolys_le_runner run -o ./out-8860 -i ./test/test_shell_input.cfg --cmd_run_file ./run_test_shell_input.sh
    - ls -la
    - ./test/test_cmp.sh ./run_test_shell_input.sh ./test/expected/run_test_shell_input.sh
    - chmod +x ./run_test_shell_input.sh
    - ./run_test_shell_input.sh
    - ./test/test.sh ./out-8860/config.out
    - ./test/test.sh ./out-8860/contact-decay_wt_N2_Moushumi2020_HIC1_5000_6_vs_X__hic_002.h5_chi2_lin.10000.png
    - ./test/test.sh ./out-8860/contact-decay_wt_N2_Moushumi2020_HIC1_5000_6_vs_X__hic_002.h5_chi2_log.10000.png
    - ls -la ./out-8860
    - ls -la ./out-8860/r2.84
    - ./test/test.sh ./out-8860/3dpoys_le.cfg
    - ./test/test.sh ./out-8860/r2.84/chip_lef.out
    - ./test/test.sh ./out-8860/r2.84/xyzconfig_001.out
    - ./test/test.sh ./out-8860/r2.84/xyzconfig_002.out
    - ./test/test.sh ./out-8860/r2.84/hic_001.hdf5
    - ./test/test.sh ./out-8860/r2.84/hic_002.hdf5
    - ./test/test.sh ./out-8860/r2.84/hic_001_hot_r.png
    - ./test/test.sh ./out-8860/r2.84/hic_002_hot_r.png
    - ./test/test.sh ./out-8860/r2.84/hic_002.hdf5.10000_decay_probs_lin.txt
    - ./test/test.sh ./out-8860/r2.84/hic_002.hdf5.10000_decay_probs_log.txt

publish_pypi_develop:
  stage: publish
  needs: [test]
  script:
    - pip install build twine
    - cat "${PYPIRC}" > ~/.pypirc
    - python -m build
    - python setup.py bdist_wheel --plat-name manylinux1-x86_64
    - twine upload --repository testpypi dist/* --skip-existing --verbose --config-file ~/.pypirc
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"

# not yet ready
#publish_pypi_master:
#  stage: publish
#  needs: [test]
#  script:
#    - pip install build twine
#    - cat "${PYPIRC}" > ~/.pypirc
#    - python -m build
#    - python setup.py bdist_wheel --plat-name manylinux1-x86_64
#    - twine upload dist/* --skip-existing --verbose --config-file ~/.pypirc
#  rules:
#    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

singularity:
  stage: production
  #image: quay.io/singularity/singularity:v3.7.3
  needs: [test]
  trigger:
    include: .singularity-ci.yml
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"
  resource_group: production
