name: py3dpolys_le
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - pip=21.2.4
  - numpy
  - pandas
  - matplotlib
  - scipy
  - filelock
  - h5py
  - dask
  - cooler
  - pyranges
  - seaborn
  #- pip:
  #    - Cython