name: py3dpolys_le
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - numpy
  - cython
  - pandas
  - matplotlib
  - scipy
  - filelock
  - h5py
  - dask
  - cooler
  - pyranges
